---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: custom-aurora
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx
image-version: stable-daily # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: bling
    install:
      - negativo17

  - type: akmods
    base: main # if not specified, classic "main" base is used by default
    install:
      - evdi

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    install:
      - ghostty
      - git-credential-oauth
      - kitty
      - neovim
      - papirus-icon-theme

  - type: fonts
    fonts:
      nerd-fonts:
        - Monaspace
        - NerdFontsSymbolsOnly
      google-fonts:
        - Inter
        - Mona Sans
        - Noto Color Emoji

  - type: initramfs

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

